version: '3.4'

services:
  parity:
    container_name: parity
    image: parity/parity:v2.3.0
    ports:
      - 8545:8545
      - 8180:8180
      - 8080:8080
      - 8546:8546
    command: $PARITY_ARGS
    volumes:
      - $PARITY_RESERVED_PEERS:/reserved_peers.txt
      - $PARITY_STORAGE:/home/parity/.local/
