version: '3.4'

services:
  parity:
    container_name: parity
    image: parity/parity:stable
    ports:
      - 8545:8545
      - 8180:8180
      - 8080:8080
      - 8546:8546
    command: $PARITY_ARGS --base-path=/home/parity/.local
    volumes:
      - $PARITY_RESERVED_PEERS:/reserved_peers.txt
      - $PARITY_STORAGE:/home/parity/.local/
    user: root
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 300M
    restart_policy:
      condition: any
      delay: 5s
      max_attempts: 10
      window: 120s
