[package]
name = "fluence-client"
version = "0.0.5"
authors = ["Fluence Labs"]
edition = "2018"

[dependencies]
particle-protocol = { path = "../../particle-protocol" }
fluence-libp2p = { path = "../../crates/libp2p" }
ctrlc-adapter = { path = "../../crates/ctrlc-adapter"}

libp2p = { git = "https://github.com/fluencelabs/rust-libp2p", branch = "neigh_debug" }

multihash ="0.11.4"
async-std = "1.6.5"
futures = "0.3.5"
futures-util = "0.3.5"
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.57"
failure = "0.1.6"
fnv = "1.0.6"
bs58 = "0.3.1"
log = "0.4.11"
env_logger = "0.7.1"
void = "1.0.2"
rand = "0.7.3"
clap = "2.33.1"

[dev-dependencies]
rand = "0.7.3"
async-std = { version = "1.6.5", features = ["unstable"] }
log = { version = "0.4.8", features = ["serde"] }
