[package]
name = "hello_world2_2018"
version = "0.1.0"
authors = ["Fluence Labs"]
publish = false
description = "Just a demo application for Fluence with logging ability"
edition = "2018"

[lib]
name = "hello_world2_2018"
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
debug = false
lto = true
opt-level = "z"
panic = "abort"

[dependencies]
log = "0.4"
fluence = { version = "0.0.12", features = ["wasm_logger"] }
