[package]
name = "fluence-sdk-macro"
version = "0.0.13"  # remember to update html_root_url
edition = "2018"
description = "Definition of `#[invoke_handler]` attribute"
documentation = "https://docs.rs/fluence/fluence-sdk-macro"
repository = "https://github.com/fluencelabs/fluence/tree/master/backend-sdk/crates/macro"
authors = ["Fluence Labs"]
keywords = ["fluence", "sdk", "webassembly", "procedural_macros"]
categories = ["api-bindings", "wasm"]
license = "Apache-2.0"
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs] # https://docs.rs/about
all-features = true

[lib]
proc-macro = true

[dependencies]
syn = { version = '0.15.0', features = ['full'] }
quote = "0.6.3"
proc-macro2 = "0.4"
fluence-sdk-main = { path = "../main", version = "=0.0.13" }
