[package]
name = "chain-listener"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethabi = { workspace = true }
thiserror = { workspace = true }
chain-data = { workspace = true }
chain-types = { workspace = true }
chain-connector = { workspace = true }

jsonrpsee = { workspace = true, features = ["ws-client", "macros", "server"] }
serde = { workspace = true }
libp2p-identity = { workspace = true }
hex-utils = { workspace = true }
hex = { workspace = true }
log = { workspace = true }
tracing = { workspace = true }
eyre = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt"]}
server-config = { workspace = true }
types = { workspace = true }

fluence-libp2p = { workspace = true }
tempfile = { workspace = true }
fs-utils = { workspace = true }
log-utils = { workspace = true }
futures = { workspace = true }
ccp-rpc-client = { git = "ssh://git@github.com/fluencelabs/capacity-commitment-prover.git", branch = "main" }
