[package]
name = "test-utils"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[dependencies]
fluence-client = { path = "../../client/rust-libp2p" }
trust-graph = { path = "../../trust-graph" }
config-utils = { path = "../config-utils" }
server-config = { path = "../server-config" }
ivalue-utils = { path = "../ivalue-utils" }
host-closure = { path = "../host-closure" }
fluence-libp2p = { path = "../libp2p" }
particle-server = { path = "../../particle-server" }
particle-protocol = { path = "../../particle-protocol" }
particle-actors = { path = "../../particle-actors" }

stepper-interface = { git = "https://github.com/fluencelabs/aquamarine", branch = "master" }
air-interpreter-wasm = { package = "air-interpreter-wasm", version = "0.0.30" }
aquamarine-vm = { git = "https://github.com/fluencelabs/fce", branch = "call_params" }

libp2p = { git = "https://github.com/fluencelabs/rust-libp2p", branch = "master" }

rand = "0.7.3"
async-std = "1.6.5"
futures = "0.3.5"
futures-util = "0.3.5"
serde_json = "1.0.57"
serde = "1.0.116"
log = "0.4.11"
env_logger = "0.7.1"
uuid = "0.8.1"
toml = "0.5.6"
prometheus = "0.9.0"
chrono = "0.4.19"
anyhow = "1.0.34"
fstrings = "0.2.3"
maplit = "1.0.2"
parking_lot = "0.11.0"
base64 = "0.13.0"
