[package]
name = "test-utils"
version = "0.3.0"
authors = ["Fluence Labs"]
edition = "2018"

[dependencies]
ivalue-utils = { path = "../ivalue-utils" }
particle-args = { path = "../particle-args" }
connected-client = { path = "../connected-client" }
created-swarm = { path = "../created-swarm" }
test-constants = { path = "../test-constants" }
service-modules = { path = "../service-modules" }

async-std = { workspace = true }
serde_json = "1.0.85"
fstrings = "0.2.3"
maplit = "1.0.2"
base64 = { workspace = true }
eyre = { workspace = true }
