## ed25519, rsa, secp256k1 private keys available for this node. Generation is available only for ed25519 and secp256k1.
## Either value or path should be defined. Value is base58 bytes.
## ed25519 format is set by default
root_key_pair.format = "ed25519"
#root_key_pair.value = "..."
root_key_pair.path = "./secret_key"
root_key_pair.generate_on_absence = true

## Services will store their data here
# default is /.fluence/v1/services
# services_base_dir = "./services"
## AIR Interpreter (stepper) will store its data here
# default is /.fluence/v1/stepper
# avm_base_dir = "./stepper"
## directory for TrustGraph certificates
# default is /.fluence/v1/certificates
# certificate_dir = "./certificates"
## directory for builtins
# default is /builtins
# builtins_base_dir = "./builtins"

## Path to AIR interpreter .wasm is set to specific version by default
## air_interpreter_path = "./aquamarine_${air_interpreter_wasm::VERSION}.wasm"

tcp_port = 7777
listen_ip = "0.0.0.0"
socket_timeout = "20s"
bootstrap_nodes = [
    "/dns4/net01.fluence.dev/tcp/7001",
    "/dns4/net01.fluence.dev/tcp/7770",
    "/dns4/net02.fluence.dev/tcp/7001",
    "/dns4/net03.fluence.dev/tcp/7001",
    "/dns4/net04.fluence.dev/tcp/7001",
    "/dns4/net05.fluence.dev/tcp/7001",
    "/dns4/net06.fluence.dev/tcp/7001",
    "/dns4/net07.fluence.dev/tcp/7001",
    "/dns4/net08.fluence.dev/tcp/7001",
    "/dns4/net09.fluence.dev/tcp/7001",
    "/dns4/net10.fluence.dev/tcp/7001"
]

websocket_port = 9999
#external_address = "85.85.35.35"
prometheus_port = 18080
stepper_pool_size = 16

## environment variables that will be passed to each service
## TODO: separate by service or move to service config
services_envs = { name = "value" }

[bootstrap_config]
reconnect_delay = "5s 500ms"
bootstrap_delay = "30s 45ms"
bootstrap_max_delay = "60s"

[root_weights]
12D3KooWB9P1xmV3c7ZPpBemovbwCiRRTKd3Kq2jsVPQN4ZukDfy = 1
12D3KooWBUJifCTgaxAUrcM9JysqCcS4CS8tiYH5hExbdWCAoNwb = 20

[protocol_config]
upgrade_timeout = "10s"
keep_alive_timeout = "10s"
outbound_substream_timeout = "10s"
