[root_weights]
Ct8ewXqEzSUvLR9CVtW39tHEDu3iBRsj21DzBZMc8LB4 = 1
5i1Jr4x6cafoSPgBEAzY62ChJun4NFXFSvsFc1SwRqWD = 20
8vn1z5pUHwX6WjCzm6RCV8kUhK1vghKSg3ktqbgnt8vv = 5
2ewYv4syQ3tzSiqigP8VRpMDi76FgrCbjebaFX3GuSDf = 6
9mw5qRU2ty78iLDz45JETdiVPr89hAASRtmxS7wrLaZF = 7
3VqV6CojVTWjL5kSgJmVeS93q3FJyc9hmMDL9i3SUWhf = 7
Ay4T8LEqmFKULQbCTYb3u2JhNRShcT2PoK2RnoxCSPmM = 10
2dGbMLB8bKzNGJQ28DjtGqLBGX3W3L9PYp4MZKQqMcTz = 2
8B1kxJeAVMXoXvzrYNeKExXd3sE1PVKC3By6v7gk5xJM = 2
6JKZnZpM9g4EgqcNGN843UfCaVpzP2Xt4j1doizhMNok = 10
2L1rDduLRDHuQJ9MBKrbRvLaxzaQJ8xFuu2Nz5R1rGx3 = 10
D9BWe9f4TgCah5EYuwKsBsv8BKNg5seMsDLR2Fp7dokh = 10
4Y9ZWhRhNMpPahtzyNefPLs9MuFoNtB3ymcpNGVSuLjx = 3
AU4Z5crLwT74kUkWojiQhCarVxZhqSs54C7SmEqaVeLL = 3
2ZYpfZQvAEDWJ8qBF9P9kFwcTJWuNXRBpVn9xKMRYFmn = 3
2MZcFRUveFyn2PyBSdmfxsH7HfQCgDNoP3De6zzCMDcw = 3
6xoTaWNXmQTKEPD1UPovMz4HqqXsJwooHoJc9rNxUjwA = 3
7LLXPHSFqbPNptr17B4cnPdux1eAZJTkkE7VBJ3KqHze = 40
2mHozVXYVRGTwjLKFUC112BjSdgqi6c9wq4pHzPYpWEV = 40
4oSYD4FPK9osNZM3nH2zKFXjri8rCsRdfansJPvs5AbQ = 40
7bkX8cLTEAGG9n6NSrjdDrk1YkkyJRPdrCjpBWkHy2Bh = 40
D5dBitVs33oNv8pmJMp2feUtMviUWhgGHM4XFKXAJMzN = 4
FmtVDk2bjnSy6A9MCPV3NzyJRDRRCU559XENEAcVWcji = 4
FdggxNBfswbCndeL5W4EcNAGSgTxQqV1gXzutA7QiEZd = 4
2pybUDrmUcqSuisqmihGerZ6qNYMc7RN8cur18qWpBQy = 4
8WFRF3bWFBoFh357tCciY1rRY4puUy4zoFpZAG1bN4RX = 4
BTjgybpQTYu8k9KC3SGTvm7dGBXLurrTVagr6Faxt8fY = 4
GojUFhCTnaRhe8vggPXpyF3pCeNoGtYyjM2yNy3xeBdk = 4
C5yYMcMCt94u51GXWru9MKFHGcgJQ29jDzhANX7iNATU = 4
AmsnWkUnbbdPPLHx7wjW4aNQQn1Xkv7Y1AAS3Lfnhguo = 4
2o7wirW2bEj6zSP6BZ3WPyiuGkzdHW2kLYDGdfzck2SH = 4

[faas]
core_modules_dir = "/wasm_modules"

[[faas.core_module]]
    name = "ipfs_node.wasm"
    mem_pages_count = 100
    logger_enabled = true

    [faas.core_module.imports]
    ipfs = "/usr/local/bin/ipfs"

    [faas.core_module.wasi]
    envs = []
    preopened_files = ["/wasm_modules"]
    mapped_dirs = { "tmp" = "/wasm_modules" }

[faas.rpc_module]
    mem_pages_count = 100
    logger_enabled = true

    [faas.rpc_module.wasi]
    envs = []
    preopened_files = ["/wasm_modules"]
    mapped_dirs = { "tmp" = "/wasm_modules" }

