[package]
name = "ivalue-utils"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[dependencies]
fluence-it-types = { git = "https://github.com/fluencelabs/interface-types", branch = "optimizations" }
serde_json = "1.0.64"
