[package]
name = "hello_world"
version = "0.1.0"
authors = ["Fluence Labs"]
publish = false
description = "Just a demo application for Fluence"
edition = "2018"

[lib]
name = "hello_world"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
fluence = { version = "0.0.12" }
