[package]
name = "particle-modules"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[dependencies]
particle-execution = { path = "../particle-execution" }

particle-args = { path = "../crates/particle-args" }
json-utils = { path = "../crates/json-utils" }
fs-utils = { path = "../crates/fs-utils" }
service-modules = { path = "../crates/service-modules" }

marine-it-parser = "0.11.0"
fluence-app-service = { workspace = true }
marine-utils = "0.4.0"

serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
toml = "0.5.9"
log = "0.4.17"
base64 = { workspace = true }
thiserror = "1.0.37"
parking_lot = { workspace = true }
eyre = { workspace = true }
fstrings = "0.2.3"
bytesize = "1.1.0"

[dev-dependencies]
tempdir = "0.3.7"
server-config = { path = "../crates/server-config" }
