[package]

name = "fluence_ethereum"
version = "0.1.0"
authors = ["Fluence Labs"]
publish = false
description = "Just takes TX from input of Fluence VM and prints them out"

edition = "2018"

[profile.release]

debug = false
lto = true
opt-level = "z"
panic = "abort"

[lib]

name = "fluence_ethereum"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]

lazy_static = "1.1.0"
log = "0.4"
fluence = { version = "0.0.6", features = ["wasm_logger", "export_allocator"] }

[dev-dependencies]

simple_logger = "1.0.1"

[replace]
"fluence:0.0.6" = {path = "/Users/trofim/Desktop/work/fluence/fluence/sdk/rust"}
