[package]
name = "tic-tac-toe"
version = "0.1.0"
authors = ["Fluence Labs"]
publish = false
description = "A tic-tac-toe example for the Fluence network"
edition = "2018"

[lib]
name = "tic_tac_toe"
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
debug = false
lto = true
opt-level = "z"
panic = "abort"

[dependencies]
log = "0.4"
arraydeque = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.38"
boolinator = "2.4.0"
fluence = { version = "0.1.0", features = ["wasm_logger"] }
simple_logger = "1.0.1"
