[package]
name = "fluence"
version = "0.0.9"  # remember to update html_root_url
description = "Rust SDK for writing applications for Fluence"
documentation = "https://docs.rs/fluence/"
repository = "https://github.com/fluencelabs/fluence/tree/master/sdk/rust"
authors = ["Fluence Labs"]
readme = "readme.md"
keywords = ["fluence", "sdk", "webassembly"]
categories = ["api-bindings", "wasm"]
license = "Apache-2.0"
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs] # https://docs.rs/about
all-features = true

[lib]
path = "src/lib.rs"

[dependencies]
log = { version = "0.4", features = ["std"] }
syn = { version = '0.15.0', features = ['full'] }
quote = "0.6.3"
proc-macro2 = "0.4"
fluence-sdk-macro = { path = "crates/macro", version = "=0.0.9" }
fluence-sdk-main = { path = "crates/main", version = "=0.0.9" }

[dev-dependencies]
simple_logger = "1.0" # used in doc test
lazy_static = "1.2.0" # used in doc test

[features]
# Turn on a compilation for module contains Wasm logger realization.
wasm_logger = ["fluence-sdk-main/wasm_logger"]

# Turn on a compilation for module contains standart implementation of allocate/deallocate functions.
export_allocator = ["fluence-sdk-main/export_allocator"]

[workspace]
members = [
  "crates/main",
  "crates/macro",
  ]
