[package]

name = "fluence_sdk"
version = "0.0.6"  # remember to update html_root_url
description="Rust SDK for writing applications for Fluence"
documentation="https://docs.rs/fluence_sdk/"
repository="https://github.com/fluencelabs/fluence/tree/master/sdk/rust"
authors = ["Fluence Labs"]
readme = "readme.md"
keywords = ["fluence", "sdk"]
categories = ["api-bindings", "wasm"]
license = "Apache-2.0"
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs] # https://docs.rs/about
all-features = true

[lib]
name = "fluence_sdk"
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]

log = { version = "0.4", features = ["std"] }

[dev-dependencies]

simple_logger = "1.0" # used in doc test
lazy_static = "1.2.0" # used in doc test

[features]

# Turn on a compilation for module 'logger' from Fluence SDK.
# This module allows logging from Wasm code.
wasm_logger = []
