[package]
name = "particle-args"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[dependencies]
ivalue-utils = { path = "../ivalue-utils" }
json-utils = { path = "../json-utils" }
control-macro = { path = "../control-macro" }

avm-server = { workspace = true }

serde_json = "1.0.85"
serde = "1.0.145"
bs58 = { workspace = true }
thiserror = "1.0.37"
eyre = { workspace = true }
