[package]
name = "particle-execution"
version = "0.1.0"
edition = "2018"

[dependencies]
particle-protocol = { path = "../particle-protocol" }

particle-args = { path = "../crates/particle-args" }
fluence-libp2p = { path = "../crates/libp2p" }
fs-utils = { path = "../crates/fs-utils" }
json-utils = { path = "../crates/json-utils" }

thiserror = "1.0.37"
futures = "0.3.24"
serde_json = "1.0.85"
